[package]
name = "workbook-fw"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = { version = "0.7.6", features = ["inline-asm"] }
embassy-executor = { version = "0.6.0", git = "ssh://git@github.com/jucr-io/embassy/", branch = "jucr_main", features = [
  "task-arena-size-32768",
  "arch-cortex-m",
  "executor-thread",
  "executor-interrupt",
  "defmt",
  "integrated-timers",
] }
embassy-rp = { version = "0.2.0", git = "ssh://git@github.com/jucr-io/embassy/", branch = "jucr_main", features = [
  "rp2040",
  "defmt",
  "unstable-pac",
  "time-driver",
  "critical-section-impl",
] }
embassy-sync = { version = "0.6.0", git = "ssh://git@github.com/jucr-io/embassy/", branch = "jucr_main", features = [
  "defmt",
] }
embassy-time = { version = "0.3.2", git = "ssh://git@github.com/jucr-io/embassy/", branch = "jucr_main", features = [
  "defmt",
  "defmt-timestamp-uptime",
] }
embassy-usb = { version = "0.3.0", git = "ssh://git@github.com/jucr-io/embassy/", branch = "jucr_main", features = [
  "defmt",
] }
embedded-hal-bus = { version = "0.1", features = ["async"] }
lis3dh-async = { version = "0.9.2", features = ["defmt"] }
panic-probe = { version = "0.3", features = ["print-defmt"] }
postcard-rpc = { version = "0.10", features = ["embassy-usb-0_3-server"] }

postcard = { version = "1.0.8", git = "ssh://git@github.com/jucr-io/postcard", branch = "jucr_main" }
postcard-schema = { version = "0.1.0", features = [
  "derive",
], git = "ssh://git@github.com/jucr-io/postcard", branch = "jucr_main" }
portable-atomic = { version = "1.9.0", features = ["critical-section"] }

workbook-icd = { path = "../workbook-icd" }

cortex-m-rt = "0.7.0"
defmt = "0.3"
defmt-rtt = "0.4"
embedded-hal-async = "1.0"
fixed = "1.23.1"
fixed-macro = "1.2"
pio = "0.2.1"
pio-proc = "0.2"
smart-leds = "0.3.0"
static_cell = "2.1"

[profile.release]
debug = 2
lto = true
opt-level = 'z'
codegen-units = 1
incremental = false

[patch.crates-io]
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-executor = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-rp = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-usb = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
embassy-usb-driver = { git = "https://github.com/embassy-rs/embassy", rev = "32cff6530fdb81066451cc1d3f1fbbb420e985da" }
postcard-rpc = { path = "../../source/postcard-rpc" }
