[package]
name = "workbook-host-client"
version = "0.1.0"
edition = "2021"

[dependencies.workbook-icd]
path = "../workbook-icd"
features = ["use-std"]

[dependencies.postcard-rpc]
version = "0.10"
features = ["use-std", "raw-nusb"]

[dependencies.postcard-schema]
version = "0.1"
features = ["derive"]
git = "ssh://git@github.com/jucr-io/postcard"
branch = "jucr_main"

[dependencies.tokio]
version = "1.37.0"
features = ["rt-multi-thread", "macros", "time"]
[patch.crates-io]
postcard-rpc = { path = "../../source/postcard-rpc" }
